site_name: 10.0.0.55 CTF Docs
site_url: http://10-0-0-55.github.io/
repo_url: https://github.com/10-0-0-55/10-0-0-55.github.io
strict: true
remote_branch: master
edit_uri: 'tree/mkdocs/docs'

nav:
    - Home: index.md
    - About: about.md
    - Web:
        - PHP: 
            - 代码审计: web/php/audit.md
            - 文件包含: web/php/LFI.md
            - 反序列化: web/php/serialize.md
        - Flask:
            - 模板注入: web/flask/ssti.md

    - Crypto:
        - Math: crypto/math.md
        - RSA:
            - CopperSmith: crypto/RSA/CopperSmith.md
        - 数字签名:
            - DSA: crypto/sign/DSA.md
    - Pwn:
        - syscall: pwn/syscall.md

theme:
    name: material
    language: zh

    hljs_languages:
        - php
        - c
        - c++
        - python

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

google_analytics:
    - UA-129115358-1
    - auto
markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - codehilite:
        guess_lang: false
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

